title: Backend Engineering Onboarding | The Iron Yard - Washington DC
project_name: Backend Engineering
description: >
  The Iron Yard - Washington DC
repository_url: https://github.com/tiy-dc-ror-2016-feb/onboarding
repository_shorthand: tiy-dc-ror-2016-feb/onboarding
class_github_org: https://github.com/tiy-dc-ror-2016-feb
baseurl: /onboarding
instructor_name: Russell Osborne
instructor_email: russell@theironyard.com
instructor_url: https://github.com/rposborne
cd_name_informal: Su
cd_name: Su Kim
cd_email: su@theironyard.com
prework_survey_1: http://goo.gl/forms/49LKcBv5tZ
prework_survey_2: http://goo.gl/forms/ePAmcTj4jA
google_analytics_uid: UA-73814182-1
collections:
  prework:
    output: true
